### ISSUE TITLE
Hi, About the Dataset of Linemod

### ISSUE THREAD

**Issue by mengfansheng16** [snilloO/obj-pose-det-seg#1]
Hi, Thank your opening source work.
Seeing that you are testing on Linemod Occlusion,
What is the test dataset you are using?
Is Occlusion_2015 ? in this websit https://hci.iwr.uni-heidelberg.de/vislearn/iccv2015-occlusion-challenge/#Hinterstoisser2012

**Comment by snilloO** [comment]
Sorry for seeing this too late, this is not an updating repo as the source code did not work well.

And I do use Linemode Occlusion from the website you mentioned.
